### ISSUE TITLE
Remove unused dependencies in setup.py

### ISSUE THREAD

**Issue by gatesn** [tomv564/pyls-mypy#1]
`future` and `configparser`, these are brought in transitively from python-language-server

**Comment by tomv564** [comment]
I brought them over as I am also using versioneer, which depends on them.

**Comment by languitar** [comment]
`configparser` is available in the python standard library? Because without removing this dependency, the plugin doesn't launch.

**Comment by tomv564** [comment]
Removed them from `install_requires` as these are dev dependencies. Thanks!

**Comment by AndreaOrru** [comment]
`future` seems to be needed - see #37
