### ISSUE TITLE
[QUESTION] How to use custom configuration?

### ISSUE THREAD

**Issue by nasyxx** [tomv564/pyls-mypy#16]
I found that your settings can't be changed.

So, if I want other settings (such as `--strict`), I can only fork it, then modify it and install it locally?

**Comment by tomv564** [comment]
A `mypy.ini` config file in your project root directory should influence the settings not specified by this plugin.

Unfortunately there is no config file equivalent of `--strict`, but running `mypy --help` should show you the config options enabled by `--strict`, to add to mypy.ini.
Hope that is convenient enough to avoid forking and locally installing the package.

I don't have time to implement and test an option for command-line extras/overrides, but you could provide them similarly to the `live_mode` setting.

**Comment by nasyxx** [comment]
I see, thank you very much.
