### ISSUE TITLE
How to disable live_mode?

### ISSUE THREAD

**Issue by nasyxx** [tomv564/pyls-mypy#17]
For this reason: https://github.com/python/mypy/issues/6070

I need to turn off `live_mode` when I use it in the emacs lsp-mode.

Normally, when I need to turn off `pycodestyle`, according to the settings here https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json . I just need to set `pyls.plugins.pycodestyle.enabled` to false.

I have tried setting both `pyls.plugins.pyls_mypy.live_mode` and `pyls.pyls_mypy.live_mode` to false, but it still in live_mode.

Did I miss something that led to the failure of the config? Or is the problem on the lsp-mode?

**Comment by tomv564** [comment]
Setting `pyls.plugins.pyls_mypy.live_mode` to false should work, unfortunately there is no logging in pyls-mypy to confirm the setting is received. You could enable more logging in python-language-server to confirm it is reading the setting and passing it to pyls-mypy?

**Comment by nasyxx** [comment]
Thank you for your answer.  I think the problem may be in the emacs lsp-mode.  But the problem is not significant. Now I use a fork version with direct default live_mode as False.
