### ISSUE TITLE
Overloads signatures

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/pyls-mypy#26]
```python
@overload
def add(x: int, y:int) -> int: ...

@overload
def add(x: int, y: float) -> float: ...

def add(x, y):
    return x + y
```
can pyls-mypy be modified send multiple signatures in this case ?

**Comment by tomv564** [comment]
What kind of output are you thinking of, completion, signature help? This plugin only handles diagnostics, the rest is all pyls. Does running “mypy” on this code give something that this plugin hides?

**Comment by tomv564** [comment]
I’m guessing it’s pyls’s use of Jedi that you are after!

**Comment by AmjadHD** [comment]
OK I opened an issue there https://github.com/palantir/python-language-server/issues/664
