### ISSUE TITLE
An overloaded function outside a stub file must have an implementation

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/pyls-mypy#30]
I'm not sure whether this is pyls-mypy, pyls or mypy's issue:
I have two files:
mod.py:
```python
def add(x, y):
    return x + y
```
and mod.pyi:
```python
from typing import overload


@overload
def add(x: int, y: int) -> int: ...


@overload
def add(x: int, y: float) -> float: ...
```
in `mod.pyi` i get this error on the first overload:
![mypy](https://user-images.githubusercontent.com/33235928/65972883-c8eaad00-e46a-11e9-864e-d22838de7b8d.png)

but when I check in the command line, I get no errors:
```sh
Microsoft Windows [version 10.0.17763.678]
(c) 2018 Microsoft Corporation. Tous droits réservés.

D:\Amjad\test_mypy>mypy mod.pyi

D:\Amjad\test_mypy>mypy mod.py

D:\Amjad\test_mypy>
```

**Comment by tomv564** [comment]
Try turning off live_mode. In live_mode mypy is not run against “mod.pyi” but only against its text as provided by pyls. Because it’s only text, mypy doesn’t know that it’s a stub file.

**Comment by AmjadHD** [comment]
> Try turning off live_mode

How do I do that ?

**Comment by AmjadHD** [comment]
Thanks @tomv564, that fixed it, but does disabling live_mode have side effects ?

**Comment by tomv564** [comment]
Updated the readme to answer your questions
