### ISSUE TITLE
Skipping analyzing error

### ISSUE THREAD

**Issue by rwols** [tomv564/pyls-mypy#43]
I never got this right in sublime text:

![Screenshot from 2020-04-12 18-19-58](https://user-images.githubusercontent.com/2431823/79074048-6d875a80-7cea-11ea-9d8c-f6453dc3f62a.png)

How do I fix this missing imports error? I'm using pyls-mypy version 0.1.8

My project settings are as follows:

```js
{
	"folders":
	[
		{
			"path": "."
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/LSP-eslint"
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/metals-sublime"
		},
		{
			"path": "/home/raoul/Documents/Programming/tonic"
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/User"
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/lsp_utils"
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/LSP-json"
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/UnitTesting"
		},
		{
			"path": "/home/raoul/.config/sublime-text-3/Packages/LSP-vue"
		},
		{
			"path": "../LSP-css"
		},
		{
			"path": "../LSP-html"
		},
		{
			"path": "../LSP-intelephense"
		},
		{
			"path": "../LSP-typescript"
		},
		{
			"path": "../LSP-elm"
		}
	],
	"settings":
	{
		"rulers":
		[
			120
		],
		"tab_size": 4,
		"translate_tabs_to_spaces": true,
		"lsp_format_on_save": true,
		"LSP":
		{
			"pyls":
			{
				"command": ["pyls"],
				"scopes": ["source.python"],
				"syntaxes": ["Packages/Python/Python.sublime-syntax"],
				"languageId": "python",
				"env":
				{
					"PYTHONPATH": "/opt/sublime_text/Lib/python33",
					"MYPYPATH": "/opt/sublime_text/Lib/python33"
				},
				"enabled": true,
			}
		}
	}
}
```

I Also tried this env:

```
				"env":
				{
					"PYTHONPATH": "/opt/sublime_text/Lib/python33",
					"MYPYPATH": "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin"
				},
```

But it doesn't seem to have any effect. I also tried this:

```
				"env":
				{
					"PYTHONPATH": "/opt/sublime_text/Lib/python33:/home/raoul/.config/sublime-text-3/Packages/LSP/plugin"
				},
```
But to no avail.

**Comment by poppyschmo** [comment]
@rwols, are you able to import `plugin.core.edit` when running `/opt/sublime_text/Lib/python33`? <del>If so, try https://github.com/tomv564/pyls-mypy/pull/45 (if you want), removing both env vars and adding</del>
```
... (stricken)
```
<del>(or similar) to `pyls.settings.pyls`. (Guesses based on [docs]; not a Sublime Text user myself.)</del>

[docs]: https://lsp.readthedocs.io/en/latest/#python

**Edit: red herring; bad advice; disregard.**

**Comment by rwols** [comment]
@poppyschmo /opt/sublime_text/Lib/python33 is a folder with two python files sublime_plugin.py  and sublime.py. I want mypy to be able to find these two files.

**Comment by rwols** [comment]
I also want mypy to be able to find `~/.config/sublime-text/Packages/LSP/plugin` as that's where `.core.edit` (core/edit.py) etc lives.

**Comment by poppyschmo** [comment]
>  /opt/sublime_text/Lib/python33 is a folder

Yikes. And here I thought it was an exe. Terrible.

Perhaps visitors to this thread more knowledgeable than I may find a working mypy command-line incantation helpful?

**Comment by poppyschmo** [comment]
@rwols I briefly tried your setup and was able to reproduce the output in your screenshot using your project settings. BTW, I see now that Sublime Text comes with Python embedded. After toggling `live_mode` **off** in `Packages/User/LSP/sublime-settings`, the import errors went away, and the output matched that given by the mypy command in your `tox.ini`.

![sublime_text_mypy](https://user-images.githubusercontent.com/12665556/81889693-09f68400-9559-11ea-9150-aa1daeff0c08.png)

As noted in the README, this means you'll have to save to trigger updates.

**Comment by rwols** [comment]
Thanks @poppyschmo turning off live-mode indeed works.
