### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by horseinthesky** [tomv564/pyls-mypy#50]
Here is my pyls config:
```
lspconfig.pyls.setup {
  cmd = {"pyls"},
  filetypes = {"python"},
  settings = {
    pyls = {
      configurationSources = {"flake8"},
      plugins = {
        jedi_completion = {enabled = true},
        jedi_hover = {enabled = true},
        jedi_references = {enabled = true},
        jedi_signature_help = {enabled = true},
        jedi_symbols = {enabled = true, all_scopes = true},
        pycodestyle = {enabled = false},
        flake8 = {
          enabled = true,
          ignore = {},
          maxLineLength = 160
        },
        pyls_mypy = {enabled = true, live_mode = true},
        pyls_isort = {enabled = true},
        yapf = {enabled = false},
        pylint = {enabled = false},
        pydocstyle = {enabled = false},
        mccabe = {enabled = false},
        preload = {enabled = false},
        rope_completion = {enabled = false}
      }
    }
  },
  on_attach = on_attach
}
```

No errors from pyls_mypy
![image](https://user-images.githubusercontent.com/19948672/113119709-6b7b1c00-9219-11eb-8445-d0c12e042b62.png)

Running mypy from shell show an error:
```
mypy bla.py
bla.py:8: error: Argument 1 to "bla" has incompatible type "int"; expected "List[str]"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by janwaldmann** [comment]
See #44 for the underlying reason. As a workaround, installing directly from the repo via
```
python -m pip install git+https://github.com/tomv564/pyls-mypy.git
```
works for me.

**Comment by horseinthesky** [comment]
@janwaldmann Works for me also. Thank you.
It seems like maintenance of pyls and its plugins is suffering from the lack of support.

I'm looking for a language server for Neovim 0.5 and the choice is `pyls` and `pyright`. I like pyls due to robust feature pack (linting and formatting) where pyright needs help of something like `efm` for formatting.
But pyls seems barely alive =(

**Comment by janwaldmann** [comment]
@horseinthesky it's a bit off-topic, but I did the very same recently and decided to use the [jedi-language-server](https://github.com/pappasam/jedi-language-server) (supports jedi 0.18; no rope) along with [diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver) for linting and formatting. Both seem to work well together in Neovim so far.

**Comment by horseinthesky** [comment]
Thanks anyway for the workaround.

**Comment by Mohan-cloud** [comment]
@horseinthesky  Is it working now? I can't get it to work even after installing the git version.

**Comment by horseinthesky** [comment]
> @horseinthesky Is it working now? I can't get it to work even after installing the git version.
Was working at that moment.

I've moved to jedi-language-server and run my flake8/mpy/black via efm-language-server. I prefer this setup now .

**Comment by Mohan-cloud** [comment]
Oh, alright! Thanks!
