### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by emmatyping** [tomv564/pyls-mypy#6]
First off, thanks for working on this! I use VS Code daily, so it is quite handy.

When I `pip install pyls-mypy` I get 

`ModuleNotFoundError: No module named 'versioneer'`

Thought I'd mention this.

I got around it by installing via git.

**Comment by tomv564** [comment]
Thanks for reporting! I cut some corners setting up versioneer, will fix in a couple of days.

**Comment by tomv564** [comment]
Fixed in latest release via https://github.com/tomv564/pyls-mypy/commit/c3b5a04fa76e15a2113a5dde470c8cd665938abe
